export const SUPPORTREGIONCONST = ["region 1", "region 2", "region 3"];

export const HOPEFUEL_ID_LISTS = [
  {
    HopeFuelID: "HOPEID - 1024",
    Name: "Mark Allen",
    Email: "susan93@evans.com",
    CardID: 56,
    TransactionDate: "2024-05-09",
    Amount: 407.7,
    CurrencyCode: "USD",
    Month: 4,
    ManyChatId: "MANY790",
    FormFilledPerson: "Allen Mark",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPEID-1025",
    Name: "Joshua Taylor",
    Email: "murillojennifer@glover-bates.org",
    CardID: 62,
    TransactionDate: "2024-02-10",
    Amount: 388.94,
    CurrencyCode: "EUR",
    Month: 9,
    ManyChatId: "MANY296",
    FormFilledPerson: "Taylor Joshua",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPEID-1026",
    Name: "Daniel Cox",
    Email: "villaapril@hotmail.com",
    CardID: 24,
    TransactionDate: "2024-10-14",
    Amount: 337.25,
    CurrencyCode: "GBP",
    Month: 6,
    ManyChatId: "MANY427",
    FormFilledPerson: "Cox Daniel",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPEID-1027",
    Name: "April Blevins",
    Email: "pearsonmarc@hammond.com",
    CardID: 16,
    TransactionDate: "2024-02-27",
    Amount: 13.6,
    CurrencyCode: "USD",
    Month: 8,
    ManyChatId: "MANY403",
    FormFilledPerson: "Blevins April",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPEID-1028",
    Name: "Mr. Michael Wilson",
    Email: "jessica43@patel-werner.info",
    CardID: 14,
    TransactionDate: "2024-06-06",
    Amount: 384.28,
    CurrencyCode: "EUR",
    Month: 3,
    ManyChatId: "MANY788",
    FormFilledPerson: "Wilson Michael Mr.",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1029",
    Name: "Stacey Cobb",
    Email: "marthacarrillo@yoder.info",
    CardID: 30,
    TransactionDate: "2024-06-08",
    Amount: 197.26,
    CurrencyCode: "CAD",
    Month: 9,
    ManyChatId: "MANY687",
    FormFilledPerson: "Cobb Stacey",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1030",
    Name: "Kathleen Strong",
    Email: "benjamin34@campos-leon.info",
    CardID: 2,
    TransactionDate: "2024-09-13",
    Amount: 205.92,
    CurrencyCode: "INR",
    Month: 4,
    ManyChatId: "MANY534",
    FormFilledPerson: "Strong Kathleen",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1031",
    Name: "Melanie Phillips",
    Email: "parkstracy@gmail.com",
    CardID: 26,
    TransactionDate: "2024-02-10",
    Amount: 281.84,
    CurrencyCode: "CAD",
    Month: 9,
    ManyChatId: "MANY635",
    FormFilledPerson: "Phillips Melanie",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1032",
    Name: "Angela Smith",
    Email: "cynthiaharris@watts.com",
    CardID: 74,
    TransactionDate: "2024-03-09",
    Amount: 113.07,
    CurrencyCode: "USD",
    Month: 7,
    ManyChatId: "MANY583",
    FormFilledPerson: "Smith Angela",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "Customer requested refund.",
  },
  {
    HopeFuelID: "HOPED-1033",
    Name: "Michael Williams",
    Email: "opeters@perez-cole.com",
    CardID: 45,
    TransactionDate: "2024-09-27",
    Amount: 134.07,
    CurrencyCode: "CAD",
    Month: 1,
    ManyChatId: "MANY577",
    FormFilledPerson: "Williams Michael",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1034",
    Name: "Shelly Gonzalez",
    Email: "eryan@gmail.com",
    CardID: 7,
    TransactionDate: "2025-01-31",
    Amount: 446.11,
    CurrencyCode: "INR",
    Month: 4,
    ManyChatId: "MANY705",
    FormFilledPerson: "Gonzalez Shelly",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1035",
    Name: "Laura Li",
    Email: "geoffrey06@ryan-randall.info",
    CardID: 66,
    TransactionDate: "2025-01-30",
    Amount: 233.72,
    CurrencyCode: "GBP",
    Month: 5,
    ManyChatId: "MANY919",
    FormFilledPerson: "Li Laura",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1036",
    Name: "Jennifer Gonzalez",
    Email: "bfisher@snyder.com",
    CardID: 35,
    TransactionDate: "2024-10-08",
    Amount: 97.06,
    CurrencyCode: "CAD",
    Month: 6,
    ManyChatId: "MANY575",
    FormFilledPerson: "Gonzalez Jennifer",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1037",
    Name: "Heidi Reed",
    Email: "imelton@gmail.com",
    CardID: 71,
    TransactionDate: "2024-09-14",
    Amount: 235.83,
    CurrencyCode: "INR",
    Month: 7,
    ManyChatId: "MANY599",
    FormFilledPerson: "Reed Heidi",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "Customer requested refund.",
  },
  {
    HopeFuelID: "HOPED-1038",
    Name: "Linda Green",
    Email: "tracy60@martin-blair.com",
    CardID: 15,
    TransactionDate: "2024-10-27",
    Amount: 414.76,
    CurrencyCode: "EUR",
    Month: 3,
    ManyChatId: "MANY244",
    FormFilledPerson: "Green Linda",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "Customer requested refund.",
  },
  {
    HopeFuelID: "HOPED-1039",
    Name: "David Palmer",
    Email: "jonesrhonda@gmail.com",
    CardID: 55,
    TransactionDate: "2024-02-22",
    Amount: 406.19,
    CurrencyCode: "EUR",
    Month: 3,
    ManyChatId: "MANY814",
    FormFilledPerson: "Palmer David",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1040",
    Name: "Michelle Warner",
    Email: "qlucas@perez.com",
    CardID: 89,
    TransactionDate: "2024-04-20",
    Amount: 218.93,
    CurrencyCode: "INR",
    Month: 3,
    ManyChatId: "MANY324",
    FormFilledPerson: "Warner Michelle",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1041",
    Name: "Crystal Shields",
    Email: "allen29@gardner.biz",
    CardID: 3,
    TransactionDate: "2024-06-30",
    Amount: 489.89,
    CurrencyCode: "GBP",
    Month: 7,
    ManyChatId: "MANY509",
    FormFilledPerson: "Shields Crystal",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "Customer requested refund.",
  },
  {
    HopeFuelID: "HOPED-1042",
    Name: "Amanda Lane",
    Email: "williamslauren@yahoo.com",
    CardID: 26,
    TransactionDate: "2024-02-04",
    Amount: 360.4,
    CurrencyCode: "CAD",
    Month: 12,
    ManyChatId: "MANY740",
    FormFilledPerson: "Lane Amanda",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1043",
    Name: "Amy Velez",
    Email: "drakelorraine@yahoo.com",
    CardID: 9,
    TransactionDate: "2025-01-30",
    Amount: 322.56,
    CurrencyCode: "GBP",
    Month: 6,
    ManyChatId: "MANY635",
    FormFilledPerson: "Velez Amy",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1044",
    Name: "Jacob Robinson",
    Email: "lancestein@hotmail.com",
    CardID: 10,
    TransactionDate: "2024-10-26",
    Amount: 359.95,
    CurrencyCode: "EUR",
    Month: 4,
    ManyChatId: "MANY192",
    FormFilledPerson: "Robinson Jacob",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1045",
    Name: "Dustin Lee",
    Email: "barrylewis@martinez-jones.com",
    CardID: 7,
    TransactionDate: "2024-08-27",
    Amount: 373.79,
    CurrencyCode: "EUR",
    Month: 5,
    ManyChatId: "MANY279",
    FormFilledPerson: "Lee Dustin",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1046",
    Name: "Kenneth Ellis",
    Email: "hooperjacob@melton.net",
    CardID: 83,
    TransactionDate: "2024-07-15",
    Amount: 184.69,
    CurrencyCode: "INR",
    Month: 5,
    ManyChatId: "MANY174",
    FormFilledPerson: "Ellis Kenneth",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "Customer requested refund.",
  },
  {
    HopeFuelID: "HOPED-1047",
    Name: "Vincent Zamora",
    Email: "anthony98@moore.com",
    CardID: 75,
    TransactionDate: "2024-10-27",
    Amount: 443.95,
    CurrencyCode: "CAD",
    Month: 12,
    ManyChatId: "MANY433",
    FormFilledPerson: "Zamora Vincent",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1048",
    Name: "Donna Stanton",
    Email: "hayeschristina@hotmail.com",
    CardID: 25,
    TransactionDate: "2024-06-11",
    Amount: 382.46,
    CurrencyCode: "CAD",
    Month: 11,
    ManyChatId: "MANY256",
    FormFilledPerson: "Stanton Donna",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1049",
    Name: "Jillian Johnson",
    Email: "christine73@rosario.net",
    CardID: 72,
    TransactionDate: "2024-10-25",
    Amount: 24.75,
    CurrencyCode: "EUR",
    Month: 11,
    ManyChatId: "MANY487",
    FormFilledPerson: "Johnson Jillian",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1050",
    Name: "Christy Davis",
    Email: "pyork@romero.com",
    CardID: 32,
    TransactionDate: "2025-01-24",
    Amount: 237.89,
    CurrencyCode: "CAD",
    Month: 9,
    ManyChatId: "MANY396",
    FormFilledPerson: "Davis Christy",
    TransactionStatus: "ဖောင်တင်သွင်းခြင်း",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1051",
    Name: "Justin Flores",
    Email: "taylorronald@hotmail.com",
    CardID: 96,
    TransactionDate: "2024-03-12",
    Amount: 362.53,
    CurrencyCode: "USD",
    Month: 1,
    ManyChatId: "MANY208",
    FormFilledPerson: "Flores Justin",
    TransactionStatus: "ငွေစစ်ဆေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1052",
    Name: "Deborah White",
    Email: "rmata@townsend.info",
    CardID: 47,
    TransactionDate: "2024-08-28",
    Amount: 81.32,
    CurrencyCode: "USD",
    Month: 2,
    ManyChatId: "MANY673",
    FormFilledPerson: "White Deborah",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "",
  },
  {
    HopeFuelID: "HOPED-1053",
    Name: "Stephanie Randall",
    Email: "burnstyler@best.com",
    CardID: 49,
    TransactionDate: "2024-11-29",
    Amount: 123.95,
    CurrencyCode: "GBP",
    Month: 3,
    ManyChatId: "MANY181",
    FormFilledPerson: "Randall Stephanie",
    TransactionStatus: "ကတ်ထုတ်ပေးပြီး",
    Note: "Customer requested refund.",
  },
];

export const HOPEFUEL_ID_LISTS_DETAILS = [
  {
    hopeId: "HOPEID-12345",
    name: "Maung Maung",
    email: "maungmaung@gmail.com",
    cardId: "12345678",
    createTime: "28-11-2024 09:55:00",
    month: 3,
    amount: 600000,
    currency: "MMK",
    formFillingPerson: "AWS-183746ag-8760-27374ytu-hfg888-dhj86879-688",
    manychatId: "77777777",
    images: [
      "https://cdn.pixabay.com/photo/2015/04/23/22/00/new-year-background-736885_1280.jpg",
      "https://cdn.pixabay.com/photo/2015/04/23/22/00/new-year-background-736885_1280.jpg",
      "https://cdn.pixabay.com/photo/2015/04/23/22/00/new-year-background-736885_1280.jpg",
    ],
  },
];

export const SUBSCRIPTION_DATA = [
  {
    HopeFuelID: 18,
    TimeLineInMonth: 3,
    MonthlyAmount: 20000,
    CurrencyCode: "JPY",
    TransactionDate: "2025-02-02T02:55:00.000Z",
    ValidFromDate: "2025-02-02T02:55:00.000Z",
    ValidThroughDate: "2025-02-20T08:30:00.000Z",
  },
  {
    HopeFuelID: 19,
    TimeLineInMonth: 3,
    MonthlyAmount: 20000,
    CurrencyCode: "MMK",
    TransactionDate: "18-12-2024 09:58:38",
    ValidFromDate: "2025-02-10T04:50:00.000Z",
    ValidThroughDate: "2025-02-17T08:09:29.000Z",
  },
  {
    HopeFuelID: 20,
    TimeLineInMonth: 3,
    MonthlyAmount: 20000,
    CurrencyCode: "USD",
    TransactionDate: "18-12-2024 09:58:38",
    ValidFromDate: "2025-02-17T08:14:04.000Z",
    ValidThroughDate: "2025-02-17T08:36:25.000Z",
  },
];

export const HISTORY_DATA = [
  {
    id: 1,
    name: "Geek Squad Studio",
    timestamp: "28-11-2024 09:55:00",
    status: "Form Opened",
  },
  {
    id: 2,
    name: "i4b Solutions",
    timestamp: "28-11-2024 09:55:00",
    status: "Form Closed",
  },
  {
    id: 3,
    name: "Queen",
    timestamp: "28-11-2024 09:55:00",
    status: "Form Opened",
  },
  {
    id: 4,
    name: "Nirvana",
    timestamp: "28-11-2024 09:55:00",
    status: "Form Closed",
  },
  {
    id: 5,
    name: "The Beatles",
    timestamp: "28-11-2024 09:55:00",
    status: "Form Opened",
  },
];

export const FUNDRAISER_DATA = [
  {
    name: "Starbucks Coffee",
    id: "12345678",
    tags: ["POS", "THE MAIL", "USD"],
    logo: "/starbucks-logo.png", // Replace with actual image paths
  },
  {
    name: "BMW",
    id: "12345678",
    tags: ["LUXURY", "BY", "THE MAIL", "USD"],
    logo: "/bmw-logo.png",
  },
  {
    name: "Apple",
    id: "12345678",
    tags: ["RETAIL", "THE MAIL", "USD"],
    logo: "/apple-logo.png",
  },
  {
    name: "Google",
    id: "12345678",
    tags: ["TECH", "THE MAIL", "USD"],
    logo: "/google-logo.png",
  },
  {
    name: "Mercedes",
    id: "34343434",
    tags: ["TECH", "THE MAIL", "USD"],
    logo: "/google-logo.png",
  },
  {
    name: "Tesla",
    id: "433434",
    tags: ["TECH", "THE MAIL", "USD"],
    logo: "/google-logo.png",
  },
];
